### PR TITLE
feat: add searchPath option

### PR DESCRIPTION
**Pull request by talzgetvim**
As an Organization, I want to be able to start up the schema registry on DB schema which isn't the public schema.

Add environment variables DATABASE_SCHEMA

### CODE REVIEW

**Comment by StarpTech** [comment]
Hi @talzgetvim thanks for the PR.

**Comment by talzgetvim** [comment]
@StarpTech, Could you please push that to Docker Hub?

**Comment by StarpTech** [comment]
I'll do it today.

**Comment by StarpTech** [comment]
Updated!

**Pull request merged**
